"""
Database models for AI Recruiter Interview System.

This module defines the PostgreSQL schema for storing interview data,
including consent tracking, call metadata, transcripts, and analytics.
"""

from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, Text, JSON, ForeignKey
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.dialects.postgresql import UUID, JSONB
from datetime import datetime
import uuid

Base = declarative_base()


class Interview(Base):
    """
    Stores interview metadata and call information.
    
    Links to candidates table via candidate_id.
    Stores Telnyx call details, consent status, and interview state.
    """
    __tablename__ = 'interviews'
    
    # Primary key
    interview_id = Column(String(64), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Foreign key to candidates table
    candidate_id = Column(String(64), nullable=False, index=True)
    
    # Job/requirement context
    job_id = Column(String(64), nullable=True)  # If you have job_postings table
    job_title = Column(String(256), nullable=True)
    job_description = Column(Text, nullable=True)  # Full JD for question generation
    
    # Consent workflow
    consent_sms_sent_at = Column(DateTime, nullable=True)
    consent_sms_sid = Column(String(128), nullable=True)  # Telnyx message SID
    consent_received = Column(Boolean, default=False)
    consent_response = Column(String(64), nullable=True)  # "YES", "NO", or actual text
    consent_timestamp = Column(DateTime, nullable=True)
    consent_form_url = Column(String(512), nullable=True)
    consent_form_signed = Column(Boolean, default=False)
    consent_form_signed_at = Column(DateTime, nullable=True)
    
    # Call scheduling
    scheduled_time = Column(DateTime, nullable=True)
    timezone = Column(String(64), default='America/Chicago')
    
    # Telnyx call metadata
    call_initiated_at = Column(DateTime, nullable=True)
    call_sid = Column(String(128), nullable=True)  # Telnyx call control ID
    call_status = Column(String(64), nullable=True)  # queued, ringing, in-progress, completed, failed
    call_duration_seconds = Column(Integer, nullable=True)
    call_answered_at = Column(DateTime, nullable=True)
    call_ended_at = Column(DateTime, nullable=True)
    
    # Recording
    recording_url = Column(String(512), nullable=True)  # Telnyx recording URL
    recording_duration_seconds = Column(Integer, nullable=True)
    
    # Interview questions (generated by LLM)
    questions = Column(JSONB, nullable=True)  # List of 6 questions
    # Format: [{"question": "...", "order": 1}, ...]
    
    # Interview state
    current_question_index = Column(Integer, default=0)
    interview_status = Column(String(64), default='pending')
    # Status: pending, consent_sent, scheduled, in_progress, completed, failed, cancelled
    
    # Interview results
    conversation_log = Column(JSONB, nullable=True)
    # Format: [{"question": "...", "answer": "...", "timestamp": "...", "confidence": 0.95}, ...]
    
    full_transcript = Column(Text, nullable=True)  # Complete transcript
    
    # Analytics (computed post-interview)
    sentiment_score = Column(Float, nullable=True)  # -1.0 to 1.0
    keyword_matches = Column(JSONB, nullable=True)  # Skills mentioned
    evaluation_score = Column(Float, nullable=True)  # 0-100
    fit_assessment = Column(String(64), nullable=True)  # strong_fit, good_fit, weak_fit
    
    # Errors and retries
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    
    def __repr__(self):
        return f"<Interview {self.interview_id} - {self.candidate_id} - {self.interview_status}>"


class InterviewTranscript(Base):
    """
    Stores individual Q&A pairs with embeddings for semantic search.
    
    This allows searching across all interview responses:
    - "Find candidates who mentioned Kubernetes in interviews"
    - "Show me all answers about leadership experience"
    """
    __tablename__ = 'interview_transcripts'
    
    # Primary key
    transcript_id = Column(String(64), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Foreign keys
    interview_id = Column(String(64), ForeignKey('interviews.interview_id'), nullable=False, index=True)
    candidate_id = Column(String(64), nullable=False, index=True)
    
    # Q&A content
    question_index = Column(Integer, nullable=False)
    question_text = Column(Text, nullable=False)
    answer_text = Column(Text, nullable=True)  # Null if candidate didn't answer
    
    # Transcription metadata
    transcription_confidence = Column(Float, nullable=True)  # Whisper confidence
    answer_duration_seconds = Column(Float, nullable=True)
    
    # Timestamps
    asked_at = Column(DateTime, nullable=True)
    answered_at = Column(DateTime, nullable=True)
    
    # Analytics
    sentiment = Column(String(32), nullable=True)  # positive, negative, neutral
    keywords_extracted = Column(JSONB, nullable=True)  # Skills/technologies mentioned
    
    # Embedding stored in separate Milvus collection
    # This table just tracks metadata; embedding goes to Milvus
    milvus_id = Column(String(64), nullable=True)  # Reference to Milvus entity
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<Transcript {self.transcript_id} - Q{self.question_index}>"


class ConsentForm(Base):
    """
    Tracks electronic consent form submissions.
    
    Stores legal compliance data for GDPR/CCPA.
    """
    __tablename__ = 'consent_forms'
    
    consent_id = Column(String(64), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Links
    interview_id = Column(String(64), ForeignKey('interviews.interview_id'), nullable=False, index=True)
    candidate_id = Column(String(64), nullable=False, index=True)
    
    # Form data
    form_url = Column(String(512), nullable=False)
    ip_address = Column(String(64), nullable=True)
    user_agent = Column(Text, nullable=True)
    
    # Consent details
    consent_text = Column(Text, nullable=False)  # What they agreed to
    signature_type = Column(String(32), default='electronic')  # electronic, typed
    signature_data = Column(Text, nullable=True)  # Base64 signature or typed name
    
    # Timestamps
    form_viewed_at = Column(DateTime, nullable=True)
    signed_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    
    # Legal
    consent_version = Column(String(16), default='1.0')
    expires_at = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<ConsentForm {self.consent_id} - {self.candidate_id}>"


# SQL creation script for PostgreSQL
SQL_CREATE_TABLES = """
-- Interviews table
CREATE TABLE IF NOT EXISTS interviews (
    interview_id VARCHAR(64) PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    job_id VARCHAR(64),
    job_title VARCHAR(256),
    job_description TEXT,
    
    consent_sms_sent_at TIMESTAMP,
    consent_sms_sid VARCHAR(128),
    consent_received BOOLEAN DEFAULT FALSE,
    consent_response VARCHAR(64),
    consent_timestamp TIMESTAMP,
    consent_form_url VARCHAR(512),
    consent_form_signed BOOLEAN DEFAULT FALSE,
    consent_form_signed_at TIMESTAMP,
    
    scheduled_time TIMESTAMP,
    timezone VARCHAR(64) DEFAULT 'America/Chicago',
    
    call_initiated_at TIMESTAMP,
    call_sid VARCHAR(128),
    call_status VARCHAR(64),
    call_duration_seconds INTEGER,
    call_answered_at TIMESTAMP,
    call_ended_at TIMESTAMP,
    
    recording_url VARCHAR(512),
    recording_duration_seconds INTEGER,
    
    questions JSONB,
    current_question_index INTEGER DEFAULT 0,
    interview_status VARCHAR(64) DEFAULT 'pending',
    
    conversation_log JSONB,
    full_transcript TEXT,
    
    sentiment_score FLOAT,
    keyword_matches JSONB,
    evaluation_score FLOAT,
    fit_assessment VARCHAR(64),
    
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE INDEX idx_interviews_candidate ON interviews(candidate_id);
CREATE INDEX idx_interviews_status ON interviews(interview_status);
CREATE INDEX idx_interviews_created ON interviews(created_at);

-- Interview transcripts table
CREATE TABLE IF NOT EXISTS interview_transcripts (
    transcript_id VARCHAR(64) PRIMARY KEY,
    interview_id VARCHAR(64) NOT NULL REFERENCES interviews(interview_id) ON DELETE CASCADE,
    candidate_id VARCHAR(64) NOT NULL,
    
    question_index INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    answer_text TEXT,
    
    transcription_confidence FLOAT,
    answer_duration_seconds FLOAT,
    
    asked_at TIMESTAMP,
    answered_at TIMESTAMP,
    
    sentiment VARCHAR(32),
    keywords_extracted JSONB,
    
    milvus_id VARCHAR(64),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transcripts_interview ON interview_transcripts(interview_id);
CREATE INDEX idx_transcripts_candidate ON interview_transcripts(candidate_id);

-- Consent forms table
CREATE TABLE IF NOT EXISTS consent_forms (
    consent_id VARCHAR(64) PRIMARY KEY,
    interview_id VARCHAR(64) NOT NULL REFERENCES interviews(interview_id) ON DELETE CASCADE,
    candidate_id VARCHAR(64) NOT NULL,
    
    form_url VARCHAR(512) NOT NULL,
    ip_address VARCHAR(64),
    user_agent TEXT,
    
    consent_text TEXT NOT NULL,
    signature_type VARCHAR(32) DEFAULT 'electronic',
    signature_data TEXT,
    
    form_viewed_at TIMESTAMP,
    signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    consent_version VARCHAR(16) DEFAULT '1.0',
    expires_at TIMESTAMP,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_consent_interview ON consent_forms(interview_id);
CREATE INDEX idx_consent_candidate ON consent_forms(candidate_id);
"""